language: node_js
node_js:
- 8.11.4
install:
  - npm install
script:              
  - npm run test
  - npm run lint
after_success:
- npm run coveralls
env:
  global:
  - secure: MCkqHGQErttW4pZP72g50pGh0unOz60Eotfcy9MZh388OxP0TFHuRg7LCmhFeijDww+eNR2VS+o6iKKNoXzPkvZw/uGE/TUbef0yGF2wajMmVZcZ1LtDaSKhaHjkQCPcCzzcPXgFcG5ApqBXN39Tglxbn3ObZmlBbY4QIKCpY6GDeOEImKBhfpygzFRC81zhgyChNjZsy8K3PgcONwh43yM2bbHjzm4iDtUmTmp8JkCSgdhN1Cf+TJePTJK6RDzZxpRPN1n79BqgMdWfdK6Nll0+2nr3iBt2vhOTAkldmvNx5auutPhpbVdhhP1vhWMJziZ/thsAdHEm3+D8krSPKEa6aOD5D+5ULLWh4WWSXK0pBW3lN1uVDR5rrCSwwCoYTM+CSt18UMjr59ZL+QZ/xOoHQy7Y+iPchB6+6HDvvQzJWxiDfiwdxof9fUv/Y4eJMEyIGjww0Mq4ZqEq9kwiySo8u/T9fR9Fhyj36Jcm0SRVcIBi7qAcCRQDtj6umjhe50pbbdAwI3ClXV1AiSgYHytfgh4q+upIuRy9glpJ5WOfuExkhn8175WByX8w/Z5ogt16skl0Y5YcP1wAVZt3eOTCf57bgtFEwsOa32TjnrF7Z+avUl+66SRFgm+26jq/8SG46zAGwL/0brNhOHL3u68GVMJrttGhpJk8qQ1n4yA=
